import type {
  AbilityCardDefinition,
  CardCatalog,
  EffectDefinition,
  ModifierKind,
  TargetDefinition,
} from '../../types.js';
const target = (
  kind: TargetDefinition['kind'],
  id = 'tower',
  options: Pick<TargetDefinition, 'count' | 'size' | 'towerTarget'> = {},
): TargetDefinition => ({
  id,
  kind,
  timing: 'on_selected',
  fallback: 'first_legal',
  ...options,
});
const own = target('own_tower');
const damaged = target('damaged_own_tower');
const visible = target('revealed_enemy_tower');
const expandable = target('expandable_tower');
const area = (size: number) => target('enemy_rectangle', 'cell', { size });
const heal = (amount: number): EffectDefinition => ({
  type: 'heal',
  trigger: 'on_selected',
  amount,
  target: 'tower',
});
const scan = (size: number): EffectDefinition => ({
  type: 'reveal',
  trigger: 'on_selected',
  target: 'cell',
  mode: 'rectangle',
  size,
});
const extra = (amount: number): EffectDefinition => ({
  type: 'extra_actions',
  trigger: 'on_selected',
  amount,
});
const hit = (amount: number): EffectDefinition => ({
  type: 'damage',
  trigger: 'on_selected',
  amount,
  target: 'tower',
});
const blast = (size: number, amount: number): EffectDefinition => ({
  type: 'area_damage',
  trigger: 'on_selected',
  target: 'cell',
  size,
  amount,
});
const build = (health: number): EffectDefinition => ({
  type: 'build_free',
  trigger: 'on_selected',
  target: 'cells',
  health,
});
const expansion: EffectDefinition = {
  type: 'expand_free',
  trigger: 'on_selected',
  target: 'tower',
  cellsTarget: 'cells',
};
const expansionTargets = (count: number) => [
  expandable,
  target('expansion_cells', 'cells', { count, towerTarget: 'tower' }),
];
const modifier = (
  kind: ModifierKind,
  amount = 1,
  target?: string,
): EffectDefinition => ({
  type: 'modifier',
  trigger: 'on_action',
  kind,
  amount,
  ...(target ? { target } : {}),
});
function card(
  id: string,
  rarityId: string,
  description: string,
  targets: TargetDefinition[],
  effects: EffectDefinition[],
  tags: string[],
  charges?: number,
  nextTurn = false,
): AbilityCardDefinition {
  const passive = effects.some((e) => e.type === 'modifier');
  return {
    id,
    version: 1,
    name: id
      .split('_')
      .map((w) => w[0]!.toUpperCase() + w.slice(1))
      .join(' ')
      .replace('All Seeing', 'All-Seeing'),
    description,
    rarityId,
    lifecycle: passive ? 'passive' : 'consumable',
    tags,
    targets,
    effects,
    eligibility: [],
    stacking: 'unique',
    visibility: 'public',
    offerWeight: 1,
    artKey: id,
    ...(passive
      ? {
          duration: {
            type: nextTurn ? 'until_owner_next_turn' : 'this_turn',
          } as const,
        }
      : {}),
    ...(charges === undefined ? {} : { charges }),
  };
}
export const launchCards: AbilityCardDefinition[] = [
  card(
    'field_repairs',
    'common',
    'Give one damaged tower +1 health.',
    [damaged],
    [heal(1)],
    ['defense', 'healing'],
  ),
  card(
    'scout_drone',
    'common',
    'Reveal a 2×2 area in one enemy quadrant.',
    [area(2)],
    [scan(2)],
    ['recon', 'fog'],
  ),
  card(
    'reinforced_walls',
    'common',
    'One tower prevents the next 1 damage it would take before your next turn.',
    [own],
    [modifier('shield', 1, 'tower')],
    ['defense', 'shield'],
    undefined,
    true,
  ),
  card(
    'surveyor',
    'common',
    'Reveal 3 orthogonally connected enemy cells.',
    [target('connected_enemy_cells', 'cells', { count: 3 })],
    [{ type: 'reveal', trigger: 'on_selected', target: 'cells' }],
    ['recon', 'fog'],
  ),
  card(
    'expansion_plans',
    'common',
    'The next time you Expand this tower this turn, it costs no action.',
    [expandable],
    [modifier('free_expand', 1, 'tower')],
    ['building', 'tempo'],
    1,
  ),
  card(
    'fresh_foundations',
    'common',
    'Your next Build this turn starts with 2 health instead of 1.',
    [],
    [modifier('build_health')],
    ['building', 'defense'],
    1,
  ),
  card(
    'rangefinder',
    'common',
    'Reveal one enemy cell. If occupied, also reveal its orthogonal neighbors.',
    [target('enemy_cell', 'cell')],
    [
      {
        type: 'reveal',
        trigger: 'on_selected',
        target: 'cell',
        mode: 'neighbors_if_occupied',
      },
    ],
    ['recon', 'fog'],
  ),
  card(
    'emergency_patch',
    'common',
    'Give one of your 1-health towers +2 health.',
    [target('one_health_tower')],
    [heal(2)],
    ['defense', 'healing'],
  ),
  card(
    'spotter',
    'common',
    'After your first Attack this turn, reveal the orthogonal neighbors of the targeted cell.',
    [],
    [modifier('spotter')],
    ['attack', 'recon', 'fog'],
    1,
  ),
  card(
    'momentum',
    'common',
    'If your first action this turn is Build or Expand, that tower gains +1 health.',
    [],
    [modifier('momentum')],
    ['building', 'healing'],
    1,
  ),
  card(
    'repair_crew',
    'uncommon',
    'Give one damaged tower +2 health.',
    [damaged],
    [heal(2)],
    ['defense', 'healing'],
  ),
  card(
    'recon_sweep',
    'uncommon',
    'Reveal a 3×3 area in one enemy quadrant.',
    [area(3)],
    [scan(3)],
    ['recon', 'fog'],
  ),
  card(
    'ambush',
    'uncommon',
    'Your first successful Attack this turn deals 2 damage instead of 1.',
    [],
    [modifier('attack_bonus')],
    ['attack', 'damage'],
    1,
  ),
  card(
    'barricade',
    'uncommon',
    'One tower prevents the next 2 total damage it would take before your next turn.',
    [own],
    [modifier('shield', 2, 'tower')],
    ['defense', 'shield'],
    undefined,
    true,
  ),
  card(
    'rapid_construction',
    'uncommon',
    'Build a 1-health tower for free.',
    [target('empty_own_cells', 'cells', { count: 1 })],
    [build(1)],
    ['building', 'tempo'],
  ),
  card(
    'rapid_expansion',
    'uncommon',
    'Expand one tower by 1 cell for free.',
    expansionTargets(1),
    [expansion],
    ['building', 'tempo'],
  ),
  card(
    'weak_point',
    'uncommon',
    'Choose a revealed enemy tower. Your next successful Attack against it this turn deals +1 damage.',
    [visible],
    [modifier('target_bonus', 1, 'tower')],
    ['attack', 'damage'],
    1,
  ),
  card(
    'counterintelligence',
    'uncommon',
    'The first time an opponent attacks one of your towers before your next turn, reveal a random hidden cell in their quadrant.',
    [],
    [modifier('counterintelligence')],
    ['defense', 'information'],
    1,
    true,
  ),
  card(
    'intelligence_network',
    'uncommon',
    'Reveal 2 random hidden cells in each active enemy quadrant.',
    [],
    [{ type: 'random_reveal', trigger: 'on_selected', amount: 2 }],
    ['recon', 'fog'],
  ),
  card(
    'engineering_crew',
    'uncommon',
    'Give one tower +1 health and Expand it by 1 cell for free.',
    expansionTargets(1),
    [heal(1), expansion],
    ['building', 'defense', 'tempo'],
  ),
  card(
    'overclock',
    'rare',
    'Gain 1 additional action this turn.',
    [],
    [extra(1)],
    ['tempo', 'actions'],
  ),
  card(
    'precision_strike',
    'rare',
    'Deal 2 damage to a revealed enemy tower.',
    [visible],
    [hit(2)],
    ['attack', 'damage'],
  ),
  card(
    'satellite_scan',
    'rare',
    'Reveal a 4×4 area in one enemy quadrant.',
    [area(4)],
    [scan(4)],
    ['recon', 'fog'],
  ),
  card(
    'fortress',
    'rare',
    'Give one tower +3 health.',
    [damaged],
    [heal(3)],
    ['defense', 'healing'],
  ),
  card(
    'double_expansion',
    'rare',
    'Expand one tower by up to 2 cells for free.',
    expansionTargets(2),
    [expansion],
    ['building', 'scoring', 'tempo'],
  ),
  card(
    'focused_fire',
    'rare',
    'After you hit a tower this turn, later Attacks against that same tower deal +1 damage.',
    [],
    [modifier('focused_fire')],
    ['attack', 'damage'],
  ),
  card(
    'forward_base',
    'rare',
    'Build a new 3-health tower for free.',
    [target('empty_own_cells', 'cells', { count: 1 })],
    [build(3)],
    ['building', 'defense', 'tempo'],
  ),
  card(
    'chain_reaction',
    'rare',
    'The first time you destroy an enemy tower this turn, gain 1 free Attack.',
    [],
    [modifier('destroy_attack')],
    ['attack', 'tempo'],
    1,
  ),
  card(
    'strategic_recon',
    'rare',
    'Reveal one full row and one full column in an enemy quadrant.',
    [target('enemy_row_column', 'cell')],
    [
      {
        type: 'reveal',
        trigger: 'on_selected',
        target: 'cell',
        mode: 'row_column',
      },
    ],
    ['recon', 'fog'],
  ),
  card(
    'reinforcement_protocol',
    'rare',
    'Give up to 3 different towers +1 health each.',
    [target('own_towers', 'tower', { count: 3 })],
    [heal(1)],
    ['defense', 'healing'],
  ),
  card(
    'air_strike',
    'epic',
    'Reveal a 3×3 area. Each enemy tower intersecting it takes 1 damage once.',
    [area(3)],
    [blast(3, 1)],
    ['attack', 'area', 'recon'],
  ),
  card(
    'heavy_artillery',
    'epic',
    'Deal 3 damage to a revealed enemy tower.',
    [visible],
    [hit(3)],
    ['attack', 'damage'],
  ),
  card(
    'mobilization',
    'epic',
    'Gain 1 extra action this turn, and your first Build or Expand this turn costs no action.',
    [],
    [extra(1), modifier('free_build_expand')],
    ['tempo', 'building', 'actions'],
    1,
  ),
  card(
    'fortification_protocol',
    'epic',
    'Every tower you own gains +1 health.',
    [],
    [{ type: 'heal_all', trigger: 'on_selected', amount: 1 }],
    ['defense', 'healing', 'wide'],
  ),
  card(
    'master_architect',
    'epic',
    'Give one tower +2 health and Expand it by up to 2 cells for free.',
    expansionTargets(2),
    [heal(2), expansion],
    ['building', 'scoring', 'defense'],
  ),
  card(
    'deep_surveillance',
    'epic',
    'Reveal a 5×5 area in one enemy quadrant.',
    [area(5)],
    [scan(5)],
    ['recon', 'fog'],
  ),
  card(
    'blitzkrieg',
    'epic',
    'Your first two successful Attacks this turn deal 2 damage each.',
    [],
    [modifier('attack_bonus')],
    ['attack', 'damage'],
    2,
  ),
  card(
    'emergency_infrastructure',
    'epic',
    'Build two separate 2-health towers for free.',
    [target('empty_own_cells', 'cells', { count: 2 })],
    [build(2)],
    ['building', 'tempo', 'defense'],
  ),
  card(
    'impenetrable',
    'epic',
    'One tower cannot take damage until the start of your next turn.',
    [own],
    [modifier('invulnerable', 1, 'tower')],
    ['defense', 'invulnerability'],
    undefined,
    true,
  ),
  card(
    'kill_chain',
    'epic',
    'Whenever you destroy an enemy tower this turn, gain a free Attack, up to 2 times.',
    [],
    [modifier('destroy_attack')],
    ['attack', 'tempo'],
    2,
  ),
  card(
    'all_seeing_eye',
    'legendary',
    "Permanently reveal one enemy player's entire quadrant.",
    [target('enemy_quadrant', 'player')],
    [
      {
        type: 'reveal',
        trigger: 'on_selected',
        target: 'player',
        mode: 'quadrant',
      },
    ],
    ['recon', 'fog', 'legendary'],
  ),
  card(
    'cataclysm',
    'legendary',
    'Reveal a 4×4 area. Each enemy tower intersecting it takes 2 damage once.',
    [area(4)],
    [blast(4, 2)],
    ['attack', 'area', 'recon', 'legendary'],
  ),
  card(
    'time_warp',
    'legendary',
    'Gain 2 additional actions this turn.',
    [],
    [extra(2)],
    ['tempo', 'actions', 'legendary'],
  ),
  card(
    'ascension',
    'legendary',
    'Give one tower +3 health and Expand it by up to 3 cells for free.',
    expansionTargets(3),
    [heal(3), expansion],
    ['building', 'scoring', 'defense', 'legendary'],
  ),
  card(
    'phoenix_protocol',
    'legendary',
    'Before your next turn, the first time you would lose your last tower, it survives with 3 health instead.',
    [],
    [modifier('phoenix', 3)],
    ['defense', 'survival', 'legendary'],
    1,
    true,
  ),
];
// Internal only: excluded from weighted rolls; guarantee distinct choices even for pathological states.
const fallbacks = [
  'neutral_reserve',
  'neutral_patience',
  'neutral_readiness',
].map((id) => ({
  ...card(
    id,
    'common',
    'No board change.',
    [],
    [{ type: 'neutral', trigger: 'on_selected' }],
    ['fallback'],
  ),
  fallbackOnly: true,
}));
export const launchCatalog: CardCatalog = {
  version: 'launch-2',
  cards: [...launchCards, ...fallbacks],
  fallbackCardIds: fallbacks.map((c) => c.id),
};
